# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: download

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       
       -  name: Display structure of downloaded files
          run: |
             echo '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' >> mytoken.txt
             cat mytoken.txt
             gh auth login --with-token < mytoken.txt
             gh run download 1
             ls
            
 
