# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: download

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
           repo:  ${{github.repository}}
           name: Specflow Test Results
           
       -  name: Display structure of downloaded files
          run: ls -R
            
 
